# Generated by Django 3.2.15 on 2022-09-02 17:43

from django.db import migrations, models
import django.db.models.deletion
import manoti.validators


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityDelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, verbose_name='Key')),
                ('value', models.CharField(max_length=200, verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, verbose_name='Key')),
                ('value', models.CharField(max_length=200, verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, verbose_name='Key')),
                ('value', models.CharField(max_length=200, verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalDocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, help_text='The full name of your Company/Organization', max_length=200, verbose_name='Name')),
                ('attachment', models.FileField(blank=True, upload_to='media/uploads', validators=[manoti.validators.validate_file_size], verbose_name='File attached')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content of the document')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingMetod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, verbose_name='Key')),
                ('value', models.CharField(max_length=200, verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, verbose_name='Key')),
                ('value', models.CharField(max_length=200, verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, verbose_name='Key')),
                ('value', models.CharField(max_length=200, verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default='Draft', max_length=200, verbose_name='Reference')),
                ('customer_reference', models.CharField(blank=True, max_length=200, null=True, verbose_name='Customer reference')),
                ('timestamp', models.DateField(blank=True, verbose_name='Date of birth')),
                ('validity_duration', models.IntegerField(help_text='days', verbose_name='Validity duration')),
                ('delivery_date', models.DateField(blank=True, verbose_name='Delivery date')),
                ('note_private', models.TextField(blank=True, null=True, verbose_name='Private note')),
                ('note_public', models.TextField(blank=True, null=True, verbose_name='Public Note')),
                ('amount_excl_tax', models.IntegerField(verbose_name='Amount (excl. tax)')),
                ('tax', models.IntegerField(verbose_name='Amount tax')),
                ('amount_incl_tax', models.IntegerField(verbose_name='Amount (inc. tax)')),
                ('availability_delay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manoti.availabilitydelay', verbose_name='Availability delay (after order)')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manoti.thirdparty', verbose_name='Third party')),
                ('document_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manoti.proposaldocumenttemplate', verbose_name='Default doc template')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manoti.paymentmethod', verbose_name='Payment method')),
                ('payment_terms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manoti.paymentterms', verbose_name='Payment terms')),
                ('shipping_metod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manoti.shippingmetod', verbose_name='Shipping Method')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manoti.source', verbose_name='Source')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Last name / Label')),
                ('first_name', models.CharField(blank=True, help_text='Keep this field empty if this is a generic address', max_length=200, verbose_name='First name')),
                ('job_title', models.CharField(blank=True, max_length=200, verbose_name='Job Title')),
                ('address', models.TextField(blank=True, help_text='Google Map URL of the contact', null=True, verbose_name='Google Map URL')),
                ('google_map', models.TextField(blank=True, help_text='Google Map URL of the contact', null=True, verbose_name='Google Map URL')),
                ('po_box', models.CharField(blank=True, help_text='Please mention the postal office box of your Company/Organization', max_length=200, null=True, verbose_name='P.O. Box')),
                ('town', models.CharField(blank=True, help_text='Indicate the town address of your contact', max_length=200, verbose_name='Town')),
                ('country', models.CharField(blank=True, default='Burundi', help_text='Indicate the country where the contact is located and/or registered', max_length=200, verbose_name='Country')),
                ('state_province', models.CharField(blank=True, default='Bujumbura', help_text='Indicate the State or Province where the contact is located and/or registered', max_length=200, verbose_name='State/Province')),
                ('phone', models.CharField(blank=True, help_text='The phone number of the contact', max_length=30, null=True, verbose_name='Phone Number')),
                ('bus_phone', models.CharField(blank=True, help_text='The Office or business phone number of the contact', max_length=30, null=True, verbose_name='Business Phone Number')),
                ('mobile_phone', models.CharField(blank=True, help_text='The mobile phone number of the contact', max_length=30, null=True, verbose_name='Mobile Phone Number')),
                ('email', models.EmailField(blank=True, help_text='The email address of the contact', max_length=255, verbose_name='Email')),
                ('is_private', models.BooleanField(default=False, verbose_name='Visibilty')),
                ('alert', models.BooleanField(default=False, verbose_name='Alerts')),
                ('date_of_birth', models.DateField(blank=True, verbose_name='Date of birth')),
                ('third_party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manoti.thirdparty', verbose_name='Third party')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manoti.title', verbose_name='title')),
            ],
        ),
    ]
