# Generated by Django 3.2.15 on 2022-10-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='total',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Total payment'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='amount_excl_tax',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Amount (excl. tax)'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='amount_incl_tax',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Amount (inc. tax)'),
        ),
        migrations.AlterField(
            model_name='proposalline',
            name='total_tax_excl',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=12, verbose_name='Total (Tax excl.)'),
        ),
        migrations.AlterField(
            model_name='proposalline',
            name='total_tax_incl',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=12, verbose_name='Total (Tax incl.)'),
        ),
        migrations.AlterField(
            model_name='proposalline',
            name='unit_price',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=12, verbose_name='Unit price'),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='remaining_unpaid',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=12, verbose_name='Remaining unpaid'),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Amount tax'),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='total_payment',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Total payment'),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='total_tax_excl',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Amount (excl. tax)'),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='total_tax_incl',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Amount (inc. tax)'),
        ),
        migrations.AlterField(
            model_name='vendorinvoiceline',
            name='total_tax_excl',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=12, verbose_name='Total (Tax excl.)'),
        ),
        migrations.AlterField(
            model_name='vendorinvoiceline',
            name='total_tax_incl',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=12, verbose_name='Total (Tax incl.)'),
        ),
        migrations.AlterField(
            model_name='vendorinvoiceline',
            name='unit_price_tax_excl',
            field=models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Unit price (net)'),
        ),
        migrations.AlterField(
            model_name='vendorinvoiceline',
            name='unit_price_tax_incl',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, verbose_name='Unit price (Tax incl.)'),
        ),
        migrations.AlterField(
            model_name='vendorinvoicepayment',
            name='amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12, verbose_name='Amount paid'),
        ),
    ]
