# Generated by Django 3.2.15 on 2022-09-02 18:20

from django.db import migrations, models
import django.db.models.deletion
import manoti.validators


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0002_availabilitydelay_contact_paymentmethod_paymentterms_proposal_proposaldocumenttemplate_shippingmetod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('sales_tax', models.IntegerField(verbose_name='Sales tax')),
                ('quantity', models.IntegerField(default=1, verbose_name='Qty')),
                ('total_tax_excl', models.IntegerField(verbose_name='Total (Tax excl.)')),
                ('total_tax_incl', models.IntegerField(verbose_name='Total (Tax incl.)')),
            ],
        ),
        migrations.CreateModel(
            name='LineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, verbose_name='Key')),
                ('value', models.CharField(max_length=200, verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, verbose_name='Key')),
                ('value', models.CharField(max_length=200, verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalLinkedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, help_text='The name of the file', max_length=200, verbose_name='Name')),
                ('attachment', models.FileField(blank=True, upload_to='media/uploads', validators=[manoti.validators.validate_file_size], verbose_name='File attached')),
                ('timestamp', models.DateField(blank=True, verbose_name='Timestamp')),
            ],
        ),
        migrations.CreateModel(
            name='StatusChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, verbose_name='Key')),
                ('value', models.CharField(max_length=200, verbose_name='Value')),
            ],
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='proposal',
            name='is_validated',
            field=models.BooleanField(default=False, help_text='Are you sure you want to validate this commercial proposal under name PR########?', verbose_name='Is the commercial proposal validated'),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.AddField(
            model_name='proposallinkedfile',
            name='proposal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manoti.proposal', verbose_name='Proposal'),
        ),
        migrations.AddField(
            model_name='line',
            name='line_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manoti.linetype', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='payment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manoti.paymenttype', verbose_name='Payment method'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manoti.statuschoices', verbose_name='Set accepted/refused'),
        ),
    ]
