# Generated by Django 3.2.15 on 2022-09-02 18:20

from django.db import migrations, models
import django.db.models.deletion
import manoti.validators


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0003_auto_20220902_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposallinkedfile',
            name='attachment',
        ),
        migrations.AddField(
            model_name='proposallinkedfile',
            name='link',
            field=models.URLField(blank=True, max_length=900, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='proposallinkedfile',
            name='save_original_name',
            field=models.BooleanField(default=False, help_text="Save file on server with name 'PR##############-Original filename' (otherwise 'Original filename')", verbose_name='Save with original file name'),
        ),
        migrations.CreateModel(
            name='ProposalAttachedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, help_text='The name of the file', max_length=200, verbose_name='Name')),
                ('attachment', models.FileField(blank=True, upload_to='media/uploads', validators=[manoti.validators.validate_file_size], verbose_name='File attached')),
                ('timestamp', models.DateField(blank=True, verbose_name='Timestamp')),
                ('proposal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manoti.proposal', verbose_name='Proposal')),
            ],
        ),
    ]
