# Generated by Django 3.2.15 on 2022-09-04 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0005_auto_20220904_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdparty',
            name='address',
            field=models.TextField(blank=True, help_text='Google Map URL of the Third party', null=True, verbose_name='Google Map URL'),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='assigned_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manoti.employee', verbose_name='Assigned representative'),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='capital',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capital'),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='country',
            field=models.CharField(blank=True, default='Burundi', help_text='Indicate the country where the Third party is located and/or registered', max_length=200, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='email',
            field=models.EmailField(blank=True, help_text='The email address of the Third party', max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='phone',
            field=models.CharField(blank=True, help_text='The Phone number of the Third party', max_length=30, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='po_box',
            field=models.CharField(blank=True, help_text='Please mention the postal office box of the Third party', max_length=200, null=True, verbose_name='P.O. Box'),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='state_province',
            field=models.CharField(blank=True, default='Bujumbura', help_text='Indicate the State or Province where the Third party is located and/or registered', max_length=200, verbose_name='State/Province'),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='town',
            field=models.CharField(blank=True, help_text='Indicate the town address of the Third party', max_length=200, verbose_name='Town'),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='website',
            field=models.URLField(blank=True, help_text='The website of the Third party', max_length=900, verbose_name='Web'),
        ),
    ]
