# Generated by Django 3.2.15 on 2022-09-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0006_auto_20220904_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdparty',
            name='name',
            field=models.CharField(help_text='The full name of the Third Party', max_length=200, verbose_name='Third party name'),
        ),
    ]
