# Generated by Django 3.2.15 on 2022-09-05 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0009_auto_20220905_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdparty',
            name='barcode',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Barcode'),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='customer_code_number',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Customer code number'),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='date_added',
            field=models.DateField(default=datetime.date(2022, 9, 5), editable=False, verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='vendor_code_number',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Vendor code number'),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='customer_code',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='Customer code'),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='Vendor code'),
        ),
    ]
