# Generated by Django 3.2.15 on 2022-09-05 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0010_auto_20220905_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdparty',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of creation'),
        ),
    ]
