# Generated by Django 3.2.15 on 2022-09-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0011_alter_thirdparty_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdparty',
            name='customer_code',
            field=models.CharField(blank=True, default='CU2209-00001', max_length=200, verbose_name='Customer code'),
        ),
    ]
