# Generated by Django 3.2.15 on 2022-09-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0012_alter_thirdparty_customer_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinvoice',
            old_name='vendor_invoice_type',
            new_name='customer_invoice_type',
        ),
        migrations.RenameField(
            model_name='customerinvoice',
            old_name='vendor_reference',
            new_name='customer_reference',
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='reference',
            field=models.CharField(default='Draft', max_length=200, unique=True, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='customer_code',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='Customer code'),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='reference',
            field=models.CharField(default='Draft', max_length=200, unique=True, verbose_name='Reference'),
        ),
    ]
