# Generated by Django 3.2.15 on 2022-09-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0013_auto_20220905_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='capital',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capital'),
        ),
    ]
