# Generated by Django 3.2.15 on 2022-09-08 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0014_alter_business_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of creation'),
        ),
    ]
