# Generated by Django 3.2.15 on 2022-09-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0015_contact_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.TextField(blank=True, help_text='The full address of the contact', null=True, verbose_name='Full address'),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
