# Generated by Django 3.2.15 on 2022-09-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0016_auto_20220911_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='customer_code_number',
            field=models.IntegerField(blank=True, default=1, null=True, unique=True, verbose_name='Customer code number'),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='vendor_code_number',
            field=models.IntegerField(blank=True, default=1, null=True, unique=True, verbose_name='Vendor code number'),
        ),
    ]
