# Generated by Django 3.2.15 on 2022-09-15 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0018_auto_20220915_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='vendor',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_vendor',
            field=models.BooleanField(default=False, help_text='Determines if either it is an incomming or outgoing purchase order, will be used whrn creating an invoice.', verbose_name='is Vendor ?'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='third_party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manoti.thirdparty', verbose_name='Third party'),
        ),
    ]
