# Generated by Django 3.2.15 on 2022-09-15 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manoti', '0019_auto_20220915_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='customer',
            new_name='third_party',
        ),
        migrations.AddField(
            model_name='proposal',
            name='author',
            field=models.ForeignKey(help_text='The user object that created this model', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='author',
            field=models.ForeignKey(help_text='The user object that created this model', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
