# Generated by Django 3.2.15 on 2022-09-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0020_auto_20220915_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalline',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='proposalline',
            name='unit_price',
            field=models.IntegerField(default=0, verbose_name='Unit price'),
        ),
        migrations.AlterField(
            model_name='proposalline',
            name='total_tax_excl',
            field=models.IntegerField(default=0, verbose_name='Total (Tax excl.)'),
        ),
        migrations.AlterField(
            model_name='proposalline',
            name='total_tax_incl',
            field=models.IntegerField(default=0, verbose_name='Total (Tax incl.)'),
        ),
    ]
