# Generated by Django 3.2.15 on 2022-09-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0022_auto_20220917_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date'),
        ),
    ]
