# Generated by Django 3.2.15 on 2022-09-17 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0023_alter_proposal_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='timestamp',
            field=models.DateTimeField(blank=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='bankaccountattachedfile',
            name='timestamp',
            field=models.DateTimeField(blank=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='bankaccountlinkedfile',
            name='timestamp',
            field=models.DateTimeField(blank=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='bankentry',
            name='date',
            field=models.DateTimeField(blank=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='bankentry',
            name='value_date',
            field=models.DateTimeField(blank=True, verbose_name='value date'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of creation'),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='date',
            field=models.DateTimeField(verbose_name='Invoice date'),
        ),
        migrations.AlterField(
            model_name='customerinvoiceattachedfile',
            name='timestamp',
            field=models.DateTimeField(blank=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='customerinvoicelinkedfile',
            name='timestamp',
            field=models.DateTimeField(blank=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='proposalattachedfile',
            name='timestamp',
            field=models.DateTimeField(blank=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='proposallinkedfile',
            name='timestamp',
            field=models.DateTimeField(blank=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of creation'),
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='date',
            field=models.DateTimeField(verbose_name='Invoice date'),
        ),
        migrations.AlterField(
            model_name='vendorinvoiceattachedfile',
            name='timestamp',
            field=models.DateTimeField(blank=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='vendorinvoicelinkedfile',
            name='timestamp',
            field=models.DateTimeField(blank=True, verbose_name='Timestamp'),
        ),
    ]
