# Generated by Django 3.2.15 on 2022-09-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0025_auto_20220921_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposallinkedfile',
            old_name='filename',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='proposallinkedfile',
            name='save_original_name',
        ),
        migrations.AlterField(
            model_name='proposalattachedfile',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='proposallinkedfile',
            name='link',
            field=models.URLField(max_length=900, verbose_name='Link'),
        ),
    ]
