# Generated by Django 3.2.15 on 2022-09-23 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manoti', '0026_auto_20220921_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='author',
            field=models.ForeignKey(help_text='The user object that created this model', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Visibilty'),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='author',
            field=models.ForeignKey(help_text='The user object that created this model', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Visibilty'),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='author',
            field=models.ForeignKey(help_text='The user object that created this model', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Visibilty'),
        ),
        migrations.AlterField(
            model_name='proposalattachedfile',
            name='attachment',
            field=models.FileField(blank=True, upload_to='media/uploads', verbose_name='File attached'),
        ),
        migrations.AlterField(
            model_name='proposallinkedfile',
            name='label',
            field=models.CharField(blank=True, help_text='Label associated with the link', max_length=200, verbose_name='Label'),
        ),
    ]
