# Generated by Django 3.2.15 on 2022-09-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0027_auto_20220923_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='label',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Label'),
        ),
    ]
