# Generated by Django 3.2.15 on 2022-09-23 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0028_bankaccount_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='label',
        ),
    ]
