# Generated by Django 3.2.15 on 2022-09-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0030_auto_20220923_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
