# Generated by Django 3.2.15 on 2022-09-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0031_alter_bankaccount_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Is this account active ?'),
        ),
    ]
