# Generated by Django 3.2.15 on 2022-09-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0032_alter_bankaccount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='entries_late_to_reconcile',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Entries late to reconcile'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='entries_to_reconcile',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Entries to reconcile'),
        ),
    ]
