# Generated by Django 3.2.15 on 2022-09-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0033_auto_20220923_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='can_be_reconciled',
            field=models.BooleanField(default=False, verbose_name='Can be reconciled'),
        ),
    ]
