# Generated by Django 3.2.15 on 2022-09-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0034_bankaccount_can_be_reconciled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankentry',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='bankentry',
            name='sens',
        ),
        migrations.AddField(
            model_name='bankentry',
            name='credit',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='bankentry',
            name='debit',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='bankentry',
            name='date',
            field=models.DateTimeField(blank=True, verbose_name='Operation date'),
        ),
        migrations.AlterField(
            model_name='bankentry',
            name='label',
            field=models.TextField(blank=True, default='Miscellaneous payment', max_length=200, verbose_name='Description/Label'),
        ),
    ]
