# Generated by Django 3.2.15 on 2022-09-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0035_auto_20220923_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankentry',
            name='category',
            field=models.CharField(blank=True, max_length=200, verbose_name='Category'),
        ),
    ]
