# Generated by Django 3.2.15 on 2022-09-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0036_bankentry_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankentry',
            options={'verbose_name': 'Bank Entry', 'verbose_name_plural': 'Bank Entries'},
        ),
        migrations.RenameField(
            model_name='bankaccountlinkedfile',
            old_name='filename',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='bankaccountlinkedfile',
            name='save_original_name',
        ),
        migrations.AddField(
            model_name='bankaccountattachedfile',
            name='save_original_name',
            field=models.BooleanField(default=False, help_text="Save file on server with name 'PR##############-Original filename' (otherwise 'Original filename')", verbose_name='Save with original file name'),
        ),
        migrations.AddField(
            model_name='proposalattachedfile',
            name='save_original_name',
            field=models.BooleanField(default=False, help_text="Save file on server with name 'PR##############-Original filename' (otherwise 'Original filename')", verbose_name='Save with original file name'),
        ),
        migrations.AlterField(
            model_name='bankentry',
            name='credit',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Credit'),
        ),
        migrations.AlterField(
            model_name='bankentry',
            name='debit',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Debit'),
        ),
    ]
