# Generated by Django 3.2.15 on 2022-09-24 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import manoti.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manoti', '0038_bankentry_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankentry',
            name='author',
            field=models.ForeignKey(help_text='The user object that created this model', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankentry',
            name='is_private',
            field=models.BooleanField(default=True, verbose_name='Visibilty'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='is_private',
            field=models.BooleanField(default=True, verbose_name='Visibilty'),
        ),
        migrations.AlterField(
            model_name='bankaccountattachedfile',
            name='filename',
            field=models.CharField(blank=True, help_text='The name of the file', max_length=300, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='BankEntryAttachedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, help_text='The name of the file', max_length=300, verbose_name='Name')),
                ('attachment', models.FileField(blank=True, upload_to='media/uploads', validators=[manoti.validators.validate_file_size], verbose_name='File attached')),
                ('timestamp', models.DateTimeField(blank=True, verbose_name='Timestamp')),
                ('save_original_name', models.BooleanField(default=False, help_text="Save file on server with name 'PR##############-Original filename' (otherwise 'Original filename')", verbose_name='Save with original file name')),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manoti.bankentry', verbose_name='Bank Entry')),
            ],
        ),
    ]
