# Generated by Django 3.2.15 on 2022-09-24 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0039_auto_20220924_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankentryattachedfile',
            old_name='bank',
            new_name='entry',
        ),
    ]
