# Generated by Django 3.2.15 on 2022-09-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0041_auto_20220924_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='is_private',
            field=models.BooleanField(default=True, help_text='Is this entry private to the the user that added it ?', verbose_name='Is private'),
        ),
    ]
