# Generated by Django 3.2.15 on 2022-09-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0043_auto_20220925_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinvoice',
            name='sku',
            field=models.CharField(blank=True, max_length=200, verbose_name='Vendor SKU'),
        ),
        migrations.AlterField(
            model_name='vendorinvoicelinkedfile',
            name='filename',
            field=models.CharField(blank=True, help_text='The name of the file', max_length=200, verbose_name='Label'),
        ),
    ]
