# Generated by Django 3.2.15 on 2022-09-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0044_auto_20220926_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorinvoice',
            name='sku',
        ),
        migrations.AlterField(
            model_name='vendorinvoice',
            name='vendor_reference',
            field=models.CharField(max_length=200, null=True, verbose_name='Reference Vendor'),
        ),
        migrations.AlterField(
            model_name='vendorinvoiceline',
            name='unit_price_tax_incl',
            field=models.IntegerField(blank=True, verbose_name='Unit price (Tax incl.)'),
        ),
    ]
