# Generated by Django 3.2.15 on 2022-09-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0045_auto_20220926_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorinvoiceline',
            name='unit_price_tax_excl',
            field=models.IntegerField(blank=True, verbose_name='Unit price (net)'),
        ),
    ]
