# Generated by Django 3.2.15 on 2022-10-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0046_alter_vendorinvoiceline_unit_price_tax_excl'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorinvoice',
            name='remaining_unpaid',
            field=models.IntegerField(default=0, verbose_name='Remaining unpaid'),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='sales_tax_is_used',
            field=models.BooleanField(default=False, verbose_name='Are Sales tax used by this thirdparty?'),
        ),
        migrations.AlterField(
            model_name='vendorinvoiceline',
            name='unit_price_tax_excl',
            field=models.IntegerField(verbose_name='Unit price (net)'),
        ),
    ]
