# Generated by Django 3.2.15 on 2022-10-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0047_auto_20221002_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentterms',
            options={'ordering': ('days',), 'verbose_name': 'Payment rerm', 'verbose_name_plural': 'Payment terms'},
        ),
        migrations.RemoveField(
            model_name='paymentterms',
            name='value',
        ),
        migrations.AddField(
            model_name='paymentterms',
            name='days',
            field=models.IntegerField(default=0, max_length=200, verbose_name='Days'),
        ),
    ]
