# Generated by Django 3.2.15 on 2022-10-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0048_auto_20221002_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentterms',
            name='days',
            field=models.IntegerField(default=0, null=True, verbose_name='Days'),
        ),
    ]
