# Generated by Django 3.2.15 on 2022-10-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0049_alter_paymentterms_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorinvoice',
            name='remaining_unpaid',
            field=models.IntegerField(blank=True, default=0, verbose_name='Remaining unpaid'),
        ),
    ]
