# Generated by Django 3.2.15 on 2022-10-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0050_alter_vendorinvoice_remaining_unpaid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorinvoice',
            name='payment_due',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Payment due on'),
        ),
    ]
