# Generated by Django 3.2.15 on 2022-10-02 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manoti', '0051_alter_vendorinvoice_payment_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manoti.business'),
        ),
        migrations.AddField(
            model_name='vendorinvoice',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manoti.business'),
        ),
    ]
