# Generated by Django 3.2.15 on 2022-10-04 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manoti', '0052_auto_20221002_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_private', models.BooleanField(default=True, help_text='Is this entry private to the the user that added it ?', verbose_name='Is private')),
                ('reference_number', models.IntegerField(default=1, verbose_name='Reference number')),
                ('reference', models.CharField(default='Draft', max_length=200, unique=True, verbose_name='Internal Reference')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('number', models.CharField(blank=True, max_length=200, verbose_name='Number (Check/Transfer N°)')),
                ('sender', models.CharField(blank=True, max_length=200, verbose_name='Sender (Check/Transfer sender)')),
                ('bank_of_sender', models.CharField(blank=True, max_length=200, verbose_name='Bank (Bank of Check)')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Private note')),
                ('total', models.IntegerField(default=0, verbose_name='Total payment')),
                ('sens', models.IntegerField(choices=[(-1, 'Credit'), (1, 'Debit')], default=1, help_text='For an accounting account of a customer, use Credit to record a payment you have received\nFor an accounting account of a supplier, use Debit to record a payment you made', verbose_name='Sense ?')),
                ('author', models.ForeignKey(help_text='The user object that created this model', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bank_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manoti.bankaccount', verbose_name='Account to Credit')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manoti.business')),
                ('payment_type', models.ForeignKey(help_text='You can change values from this list from the Setup >> Dictionnaries', null=True, on_delete=django.db.models.deletion.CASCADE, to='manoti.paymenttype', verbose_name='Payment type')),
                ('third_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manoti.thirdparty', verbose_name='Company')),
            ],
        ),
    ]
